# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banid', models.IntegerField()),
                ('coverUrl', models.CharField(max_length=30)),
                ('bantype', models.IntegerField()),
                ('webUrl', models.CharField(max_length=30)),
                ('trendId', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BriefGym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gymid', models.IntegerField()),
                ('gymName', models.CharField(max_length=30)),
                ('gymCover', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
                ('gymAvatar', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('isCoop', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BriefUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('userName', models.CharField(max_length=30)),
                ('userAvatar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromHour', models.IntegerField()),
                ('fromMinite', models.IntegerField()),
                ('toHour', models.IntegerField()),
                ('toMinite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailGym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefGym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.BriefGym')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('equipmentType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GymCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardType', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('userkey', models.CharField(max_length=30)),
                ('cmdid', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('version', models.CharField(max_length=30)),
                ('platform', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('message', models.CharField(max_length=30)),
                ('cmdid', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField()),
                ('gymid', models.IntegerField()),
                ('gymName', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30)),
                ('imgs', models.IntegerField()),
                ('likeCount', models.IntegerField()),
                ('commentCount', models.IntegerField()),
                ('isLiked', models.BooleanField()),
                ('briefUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.BriefUser')),
            ],
        ),
        migrations.AddField(
            model_name='detailgym',
            name='equipments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.Equipment'),
        ),
        migrations.AddField(
            model_name='detailgym',
            name='gymCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.GymCard'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.CourseTime'),
        ),
    ]
