# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefGym',
            fields=[
                ('gymid', models.IntegerField(primary_key=True, serialize=False)),
                ('gymName', models.CharField(max_length=30)),
                ('gymCover', models.URLField()),
                ('place', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('info', models.CharField(max_length=300)),
                ('signTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BriefUser',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('userPhone', models.CharField(max_length=13)),
                ('userPW', models.CharField(max_length=30)),
                ('userCover', models.URLField()),
                ('userSex', models.BooleanField()),
                ('userSign', models.CharField(max_length=30)),
                ('Xbin', models.IntegerField()),
                ('signTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Commentid', models.IntegerField(primary_key=True, serialize=False)),
                ('CommentUser', models.IntegerField()),
                ('Comment', models.CharField(max_length=300)),
                ('CommentTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('week', models.IntegerField()),
                ('fromHour', models.IntegerField()),
                ('fromMinite', models.IntegerField()),
                ('toHour', models.IntegerField()),
                ('toMinite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailGym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gymid', models.IntegerField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('equipmentType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('Followid', models.IntegerField(primary_key=True, serialize=False)),
                ('FollowTime', models.DateTimeField()),
                ('Follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.BriefUser')),
            ],
        ),
        migrations.CreateModel(
            name='GymCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardType', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gyminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gymid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.BriefUser')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('imageid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likeid', models.IntegerField()),
                ('LikeUser', models.IntegerField()),
                ('LikeTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('Trendid', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=30)),
                ('Userid', models.IntegerField()),
                ('Gymid', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('imgs', models.URLField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.Comment')),
                ('likeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.BriefUser')),
            ],
        ),
        migrations.CreateModel(
            name='xbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detbin', models.IntegerField()),
                ('reason', models.CharField(max_length=30)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.BriefUser')),
            ],
        ),
        migrations.AddField(
            model_name='detailgym',
            name='equipments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.Equipment'),
        ),
        migrations.AddField(
            model_name='detailgym',
            name='gymCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.GymCard'),
        ),
        migrations.AddField(
            model_name='briefgym',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.Course'),
        ),
        migrations.AddField(
            model_name='briefgym',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.Equipment'),
        ),
        migrations.AddField(
            model_name='briefgym',
            name='GymCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.GymCard'),
        ),
    ]
