# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Background', '0017_tblbriefuser_hadreadmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TblCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.TblCourse')),
            ],
        ),
        migrations.AddField(
            model_name='tblbriefgym',
            name='courseBrief',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tblbriefgym',
            name='equipmentBrief',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tblbriefuser',
            name='lastShow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Background.TblBriefGym'),
        ),
        migrations.AlterField(
            model_name='tblbriefuser',
            name='userName',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tblbriefuser',
            name='userSign',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tblcommentmessage',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tbltrend',
            name='content',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='tbltrendcomment',
            name='comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='user_course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.TblBriefUser'),
        ),
        migrations.AddField(
            model_name='tblcoach',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Background.TblBriefUser'),
        ),
        migrations.AddField(
            model_name='tblcoach',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.TblBriefGym'),
        ),
        migrations.AddField(
            model_name='coach_course',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.TblCoach'),
        ),
        migrations.AddField(
            model_name='coach_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Background.TblCourse'),
        ),
    ]
