# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Background', '0018_auto_20160602_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbriefgym',
            name='geohash',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
