# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Background', '0019_tblbriefgym_geohash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbriefuser',
            name='geohash',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
