# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reader.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reader.proto',
  package='com.xiang.proto.reader',
  syntax='proto3',
  serialized_pb=b'\n\x0creader.proto\x12\x16\x63om.xiang.proto.readerb\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





# @@protoc_insertion_point(module_scope)
